### ISSUE TITLE
Set the current playing track

### ISSUE THREAD

**Issue by gruhn** [spotify/web-playback-sdk#1]
First of all thanks for dropping the Web Playback SDK. I've been looking forward for something like this a long time :grin::+1: 

Please correct me if I'm wrong but after browsing the docs I can't find any way to manipulate which specific tracks are played. Neither using the Web Playback SDK nor the Web API. This feature would be essential for my use case.

I'm building a web app that allows a group of people to collectively assemble a playlist. Everybody can suggest tracks and everybody else can agree or disagree. The tracks, most users agree with, are continuously played. This is mainly intended to be used on parties so users can reach consensus on which music they like to hear. 

Therefore I need a way to tell a player which tracks to play. The ability to push tracks in the players queue would also be sufficient I guess.

**Comment by gruhn** [comment]
Ah thanks! I'll read the docs more careful next time 👍

**Comment by bih** [comment]
No worries, you’re good! Merry Christmas!
