### ISSUE TITLE
Player play one of my track in "Your Top Songs 2019" playlist not my selected track.

### ISSUE THREAD

**Issue by Vietvantue** [spotify/web-playback-sdk#101]
My website enables users search track and play track via Spotify. Some days ago, my users report that it doesn't play the song they chose. I try by myself and it happen to me also. Now, more user report this issue and I also can test in by my side.

Issue found on from Jan 17 2020 and still observed on Jan 19 2020.
Some more notices:
+ I double check, my code pass uris with only 1 track_id, I don't pass context_uri to player.
+ Noone using my account, I did reset password again and again then SIGN OUT EVERYWHERE before make testing.
+ My Spotify account is Premium already, it works charming before and only face the problem recently.
#### Steps to reproduce:
1. Search a list of tracks by keyword.
2. Select a track and play track as this demo: https://developer.spotify.com/documentation/web-playback-sdk/reference/#playing-a-spotify-uri
3. Observe, usually it plays "Señorita" not my selected track. (Señorita is first track of my Top Songs 2019 list, I guess it is auto generated by Spotify?)

#### Expected behaviour:
It should play my selected tracks.
#### Actual behaviour:
It always play the first track of my "Top Songs 2019"

**Comment by kuplix** [comment]
The same issue is happening with us. We are specifying a single track_id to be played but instead, the response from Spotify indicates a context_uri of an auto-generated playlist from Spotify. As a result, the playback continues to random tracks in that auto playlist.

We thought of specifying a context_uri of an empty playlist but that didn't work out and the documentation at https://developer.spotify.com/documentation/web-api/reference/player/start-a-users-playback/ indicates that you can only specify EITHER uris OR a context_uri but not both.

**Comment by andreadipalma** [comment]
Experiencing the same issue here. On the web application, the spotify SDK player invokes the REST API to play a specific track_id selected, but it starts playing a different track. I tested it and noticed that the track player is connected with the history of tracks played by the user on the premium account.

**Comment by anker2000** [comment]
I'm having the exact same issue and I think it's somehow related to [https://github.com/spotify/web-playback-sdk/issues/99](url)

**Comment by adrianosbr** [comment]
I'm experiencing the same problem. From some days ago, the Web API is facing big trouble to populate the play queue. It fails most of the time and the web player keeps playing the old queue, generated by the Spotify official app, instead.

**Comment by JasonZigelbaum** [comment]
Yeah same problem here. Our users are getting the last played song (from Spotify) and not the track URI that was actually sent. It seems to happen somewhat sporadically but pretty often (at least once per hour).

**Comment by hiei189** [comment]
Same issue as well. It plays my users last played song. Does anyone know a workaround?
