### ISSUE TITLE
web Player is prioritizing spotify player play queue

### ISSUE THREAD

**Issue by humusdigital** [spotify/web-playback-sdk#103]
Issue found on *20/02/2019*.

#### Steps to reproduce:
1. via js set a track into web-playback-sdk
2. The web player some times play a track from spotify play queue and not the correct track set via js.

**Comment by anker2000** [comment]
Looks like a duplicate of #99

**Comment by joshubrown** [comment]
We made some updates earlier this week that should resolve the problem with API-initiated playback. If you are still experiencing the issue then please let us know 🙂
