### ISSUE TITLE
problems after token renew

### ISSUE THREAD

**Issue by toldap** [spotify/web-playback-sdk#109]
hi all

my token is continuously renewed in the background and stored in the variable TOKEN at the front. everything actually works perfectly. only, as soon as the token is renewed, I can no longer put the player on "pause" and if another playlist is selected, it plays both together on the same player. 

does anyone know?

my code:
// Spotify WebPlayer
window.onSpotifyWebPlaybackSDKReady = () => {
const token = TOKEN;
const player = new Spotify.Player({
name: NAME,
getOAuthToken: cb => { console.error("Token sollte erneuert werden");cb(token); }
});

many thanks,
toldap

**Comment by UlysseM** [comment]
well, you're copying the "TOKEN" variable into a cost token (not copying its reference).
So when you call cb(token), you're passing the TOKEN at the time onSPotifyWebPlaybackSDKReady was created, and if you change TOKEN, token will remain the same.

Calling cb(TOKEN) should work for you.

**Comment by toldap** [comment]
hi UlysseM

thanks for your help.

unfortunately it still doesn't work. For better understanding I have renamed the variables. The variable SPOTIFYTOKEN is automatically updated in the background. 

So this code:
// Spotify WebPlayer
window.onSpotifyWebPlaybackSDKReady = () => {
const token = SPOTIFYTOKEN;
const player = new Spotify.Player({
name: SPOTIFYNAME,
getOAuthToken: cb => { console.error("Token sollte erneuert werden");cb(token)}
});

behaves the same like this code;
// Spotify WebPlayer
window.onSpotifyWebPlaybackSDKReady = () => {
const token = SPOTIFYTOKEN;
const player = new Spotify.Player({
name: SPOTIFYNAME,
getOAuthToken: cb => { console.error("Token sollte erneuert werden");cb(SPOTIFYTOKEN)}
});

It is still the case that as soon as the token is renewed for the first time, the playlists are played in parallel and also for example the pause function over the API does not work either. 

thanks again,
toldap

**Comment by toldap** [comment]
hi,

That was an incorrect configuration on my side. 
I also incorrectly set the SPOTIFYNAME variable too,
whenever the token was renewed.

thanks
