### ISSUE TITLE
GET https://api.spotify.com/v1/melody/v1/check_scope: 403 status when connecting Player

### ISSUE THREAD

**Issue by paulgoetze** [spotify/web-playback-sdk#11]
Issue found on *30.01.2018*.

#### Scope(s): 
* user-read-email 
* streaming 
* user-modify-playback-state 
* user-read-playback-state 
* user-read-currently-playing

#### Steps to reproduce:
1. Fetch access token with the scopes
2. Initialize Spotify.Player with the received token
3. connect the Player

#### Expected behaviour:
`GET https://api.spotify.com/v1/melody/v1/check_scope` should succeed.

#### Actual behaviour:

When connecting a player object with a valid token the SDK seems to file a GET request to
`https://api.spotify.com/v1/melody/v1/check_scope?scope=web-playback`
which returns with a 403 status with the response

```
{"error":"Token does not satisfy scope."}
```

However, I cannot find the given `web-playback` scope in the API docs and when I add it to the scopes when fetching an access token, it is reported to be an invalid scope.

Playing tracks etc. does work anyways. It seems like this error should not appear though. Or is there just a scope missing when authenticating?

**Comment by bih** [comment]
Hey @paulgoetze!

Thanks for filing the error! I tried to replicate the issue, but I was given an empty response with a `200 OK` response status.

As per [the Web Playback SDK docs](https://beta.developer.spotify.com/documentation/web-playback-sdk/), you should request the following scopes: `["streaming", "user-read-birthdate", "user-read-email", "user-read-private"]`

Can you share what scopes you are using?

**Comment by paulgoetze** [comment]
@bih The scopes list is given above ;)

**Comment by bih** [comment]
Ah okay, I must've missed that.

I have found the issue, however. It seems like you're missing two required scopes from your list: `["user-read-private", "user-read-birthdate"]`

If you can add both of them, that error will go away. I'll go ahead and close this issue as this has a known fix. If that doesn't work, feel free to re-open the issue and we'll take a look again 👍

**Comment by paulgoetze** [comment]
Thanks @bih, just tried it with the additional scopes, that solves it! 

However, whereas `user-read-private` absolutely makes sense for private playlists etc., why would I need the user’s birthdate for the player?

**Comment by bih** [comment]
Glad to hear!

That's a fair question. We require the `user-read-birthdate` for the Web Playback SDK because it is necessary for us to perform validation on the authenticated user's Premium subscription. And as the SDK only supports Spotify Premium users, we require it by default for all use cases.

Hope this helps!

**Comment by okjuan** [comment]
This fixed my issue too. Sidenote: it seems `user-read-birthdate` is now deprecated.

**Comment by bh90210** [comment]
for anyone reaching here from the future for now these are the required scope for sdk to work
```
Required scopes: ["streaming", "user-read-email", "user-read-private"]
```
from https://developer.spotify.com/documentation/web-playback-sdk/quick-start/
