### ISSUE TITLE
Cannot remove event handlers

### ISSUE THREAD

**Issue by NeoLegends** [spotify/web-playback-sdk#12]
Hey,

I just noticed you cannot remove event listeners registered on the `Spotify.Player` once you registered them. This should be fixed.

**Comment by Sigmus** [comment]
Just curious, what's your use case for wanting to unbind events?

**Comment by arirawr** [comment]
Hey @NeoLegends! Thanks for the request! We'd also love to hear more about your use case and how adding this functionality would help you.

**Comment by NeoLegends** [comment]
Well, we create multiple players over the course of the lifetime of the application (of which only a single one is playing / „active“), and old players should not be able to publish their events to the app anymore. Right now we‘re working around that by setting a flag inside the listener once we want to „unlisten“, but that feels hacky.

**Comment by arirawr** [comment]
Could you disconnect from the player using `Spotify.Player.disconnect()` instead? (docs: https://beta.developer.spotify.com/documentation/web-playback-sdk/reference/#api-spotify-player-disconnect)

**Comment by NeoLegends** [comment]
I can, but unregistering event handlers is more about preventing memory leaks, I guess.

**Comment by bih** [comment]
@NeoLegends Thanks for the feedback! We should have a solution deployed soon 👍

**Comment by NeoLegends** [comment]
Great! 👍 I'll update the TS definitions accordingly.

**Comment by arirawr** [comment]
This has been updated in the latest version! Here's the new documentation for `removeListener`: https://beta.developer.spotify.com/documentation/web-playback-sdk/reference/#api-spotify-player-removeListener

**Comment by NeoLegends** [comment]
Do I see that right, that `player.on` was removed (or at least hidden) in favor of `addListener`?

**Comment by bih** [comment]
@NeoLegends We decided to favour `addListener`. Don't worry, both `player.on` and `player.addListener` still work so integrations shouldn't break 👍

**Comment by NeoLegends** [comment]
Ok, so I'll remove `.on` from the typings then. :)

**Comment by NeoLegends** [comment]
Great work btw, thanks for the addition!

**Comment by bih** [comment]
@NeoLegends Happy to help - thanks so much for the feedback! 👏

**Comment by NeoLegends** [comment]
Hmm, I'm still thinking about removing `.on` from the typings. Do you intend to keep that method or do you want to deprecate that after a while? Leaving it in would make the typings backwards compatible.

**Comment by bih** [comment]
@NeoLegends We originally were planning to have `.on` and `.removeListener` but that can easily be confusing to developers, hence why we added the alias. There are absolutely no intentions of removing `.on` anytime soon. Feel free to leave it in, it was just to make things easier for developers :)

**Comment by NeoLegends** [comment]
Here we go: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/23819

**Comment by NeoLegends** [comment]
Merged.
