### ISSUE TITLE
/v1/track-playback/v1/devices - Service didn't reply before timeout (504)

### ISSUE THREAD

**Issue by vietnt-uet** [spotify/web-playback-sdk#120]
Issue found on *May 07 2020*.

#### Steps to reproduce:
1. Init web playback player with access_token and wait for **ready** event (return device_id)
2. Observe /v1/track-playback/v1/devices failed several times or all times
`{
  "error": {
    "status": 504,
    "message": "Service didn't reply before timeout"
  }
}`
3. Observe it takes a long time to ready and return device_id or never fire **ready** event.

#### Expected behaviour:
**Ready** event fired when init player with valid access_token.
#### Actual behaviour:
**Ready** event not fired or taking a long time to be fired.

**Comment by cc-plm** [comment]
I got the same issue today: #121 
I believe that we opened these issues at the same time, I didn't notice this one until after I already posted mine.
