### ISSUE TITLE
Getting an "invalid syntax" console error when using Web Playback as a free user

### ISSUE THREAD

**Issue by Aakanksha345** [spotify/web-playback-sdk#13]
Issue found on *DATE*.: 14/2/2018

#### Steps to reproduce:
1.  Used quick start guide: https://beta.developer.spotify.com/documentation/web-playback-sdk/quick-start/

2.  used free account to connect to api.
3. Got 400 error 

Attached screenshot
![image](https://user-images.githubusercontent.com/25923578/36220555-083e6590-11e1-11e8-9640-1cb7f7fea83a.png)

#### Actual behaviour:
HTTP400: BAD REQUEST - The request could not be processed by the server due to invalid syntax.
(Fetch)DELETE - https://api.spotify.com/v1/me/notifications/user?connection_id=Njg4YWUwNjQtZDFiYS00ZmI4LTgxZmYtMzg4YWJiZDMzNzJhK2RlYWxlcit0Y3A6Ly9nYWUyLWRlYWxlci1iLWJra3EuZ2FlMi5zcG90aWZ5Lm5ldDo1NzAwK0I2NTBDQzZEOERGMEEzNjQ0MTAzOURDRTBEMjFCMkQ0MjZEOThDMkY2RjE4QjJDQjhBNDYyMjQyNEQzMUNCNjk%3D

**Comment by bih** [comment]
Hi @Aakanksha345,

As mentioned in the [Web Playback docs](https://beta.developer.spotify.com/documentation/web-playback-sdk/), the SDK only works for Spotify Premium users. You won't be able to get it working at all with a free account.

With that being said, if you are not Spotify Premium, you would receive a `account_error` event in the SDK and not the error you're experiencing. Because of this I'll treat it as a bug report.

Can you share more of which browser you're using? We'll investigate 👍

**Comment by Aakanksha345** [comment]
Thanks but I am using a premium account and using it on Microsoft edge. Could you please share your skype id so that I can share my screen.

Also I need your help to understand some more things as we want to use Spotify in one of our projects so wanted to understand that part also.

Regards,
Aakanksha

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by bih** [comment]
Hey @Aakanksha345,

To be fair to other developers viewing this thread now (and in the future), we should keep all communication on this thread. That being said, we're happy to talk over email about anything that specifically requires non-public information (i.e. such as your Client ID and Secret).

If you have other questions outside the scope of this issue, feel free to create an issue and tag it under "question" and we'll take a look 👍

**Comment by Aakanksha345** [comment]
Please share your email id so that we can talk regarding the scenario I have mentioned.

Regards,
Aakanksha

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by bih** [comment]
@Aakanksha345 My email address is on my profile 👍

**Comment by Aakanksha345** [comment]
Thanks shared one email.

Regards,
Aakanksha

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by bih** [comment]
@Aakanksha345 Can you confirm you're still getting an error here?

**Comment by arirawr** [comment]
Hi @Aakanksha345 - I'm going to close this issue as it appears to have been resolved. If you are still seeing the behaviour, please feel free to reopen!
