### ISSUE TITLE
Spotify Authentication Tutorial not working

### ISSUE THREAD

**Issue by syan0127** [spotify/web-playback-sdk#17]
Issue found on Feb 24th, 2018

Scope(s):
"user-read-private", "user-read-email"

Steps to reproduce:
- Did everything in the tutorial

Expected behaviour:
- Successful login

Actual behaviour:
- Login failed message

**Comment by syan0127** [comment]
I am using a free account for this. For my understanding authentication does not require a premium account

**Comment by bih** [comment]
Hey @syan0127,

Authentication itself does not require a Premium account, that would be a bug. However the Web Playback SDK is Premium-only. Can you update your "Steps to reproduce" to be a specific as possible so I can reproduce this? Cheers!

**Comment by arirawr** [comment]
Closing this issue as we haven't been able to reproduce the behaviour. Feel free to reopen with reproduction steps if you are still seeing the issue!
