### ISSUE TITLE
Platform does not support navigator.requestMediaKeySystemAccess()

### ISSUE THREAD

**Issue by njtrettel** [spotify/web-playback-sdk#2]
Issue found on *12/21/17*. Supported by Chrome 42+ according to [MDN docs](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/requestMediaKeySystemAccess). This might just be an issue with my AWS environment, but I can't find any solutions. 

#### Scope(s):
Creating Spotify Player from AWS instance
Chrome 63
Node.js server

#### Steps to reproduce:
1. Deploy an app utilizing Spotify Playback SDK to AWS
2. Notice the initialization error, 
```
{
  code: "LIST_PLAYER_NO_TRACK_PLAYER",
  debug: {},
  listPlayerIgnore: false,
  message: "Platform does not support navigator.requestMediaKeySystemAccess",
  unrecoverable: false
}
```

#### Expected behaviour:
Normal error free initialization.
I haven't had any issues with this locally. I've been reading more about EME and how the keySystem works but the only thing I can find that would cause this is browser compatibility. I used the same browser and machine testing locally and with this AWS instance. 

#### Actual behaviour:
The above error is happening on initialization and when I try to play a song. 

Not sure what the difference would be between my local and AWS environment. Tried to step through the bundled code but man that's rough... Google Chrome couldn't "prettify" it for me 😄

**Comment by arirawr** [comment]
Hi @njtrettel - are you accessing your AWS instance over HTTP or HTTPS? In Chrome, [EME will not work in non-secure contexts](https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/tXmKPlXsnCQ/discussion) (ie. over HTTP).

**Comment by njtrettel** [comment]
@arirawr ohh of course. thanks, I am definitely doing that just for early testing purposes. I didn't think this would be an issue because it works when i run it locally. Is localhost via HTTP still considered a "secure context" because it is just localhost? I don't have the means to test this out yet but I will move it to HTTPS as soon as I do.

**Comment by arirawr** [comment]
Yes it is! https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts

I'm going to go ahead and close this issue - happy hacking!
