### ISSUE TITLE
Feature request: Expired token callback

### ISSUE THREAD

**Issue by fafcrumb** [spotify/web-playback-sdk#20]
The current callback `getOAuthToken` works correctly. However, it's wasteful in that there's no way for a client app to differentiate when `getOAuthToken` is run because the token expired, or because of some other reason, such as a network change/interruption, waking from sleep, or even a browser refresh. Because of this, the client must run the full server-side refresh token flow to guarantee a new token every time, when a valid token could have already been sitting in memory. The `authentication_error` event doesn't help either since it's only fired after multiple retries of `getOAuthToken`.

A callback similar to `getOAuthToken` that's called as soon as the sdk detects it has an expired token would be fantastic to have. A `token_expired` event would also work, but isn't ideal.

Thanks!

**Comment by NeoLegends** [comment]
When you are given an access token from the Web API, you are also given its expiration date (see https://beta.developer.spotify.com/documentation/general/guides/authorization-guide/#authorization-code-flow). Thus, you can cache the token locally as long as its valid and only refresh it with the server when needed. So there's no need for an additional callback.

**Comment by fafcrumb** [comment]
Well not **exactly**. You're given the amount of time until it expires in seconds. So then you'll need to create a new date based on that -> save it to your database -> retrieve it with your token -> compare against the current date in the callbavk
