### ISSUE TITLE
Player 401 unauthorised after long usage

### ISSUE THREAD

**Issue by JackRyder** [spotify/web-playback-sdk#23]
Issue found on 27-03-2018.

#### Scope(s):
Scope.UserReadPrivate | Scope.PlaylistReadPrivate | Scope.PlaylistReadCollaborative | Scope.Streaming | Scope.UserReadEmail | Scope.UserReadBirthdate

#### Steps to reproduce:
1. play music for a long period of time over and over, passing songs in manually
2. eventually the player 401s and you have to restart to get a new token / get everything to work again.

#### Expected behaviour:
Player continues running after token expires, because apparently you don't need to reauth the playback sdk.

#### Actual behaviour:
Player stops running, returning 401 unauthorised on "gew.spotify" or something like that, which i'm assuming is the iframe this runs in.

I just need some solid insight to refreshing the token if needed to be honest, would i just need to create a new instance of the player object whenever it 401s?

**Comment by hughrawlinson** [comment]
Hi!

> apparently you don't need to reauth the playback sdk.

Could you point us to where you read that so that we can correct it? The web playback sdk will request a fresh token when it needs one.

Seems like this is expected behaviour, so I'll close this issue, but please let me know if there's some documentation I should update.

Best,

Hugh
Spotify Developer Support

**Comment by JackRyder** [comment]
Hey,

Where is the documentation regarding refreshing the playback sdk token when it asks? I cannot find anywhere which allows me to cleanly give it a new token.

**Comment by fafcrumb** [comment]
This is the only place that references giving a _new_ token to the sdk. I agree the docs could be a little more clear on this.

https://beta.developer.spotify.com/documentation/web-playback-sdk/reference/
<img width="925" alt="screen shot 2018-03-29 at 1 01 10 pm" src="https://user-images.githubusercontent.com/17421035/38102495-69d14232-3351-11e8-90b8-209d0bebf3a2.png">

The sdk will call getOAuthToken when the token expires. This is where you'll need fetch a new token and provide it to the callback.

**Comment by JackRyder** [comment]
Ah right okay, this makes much more sense, thank you.

**Comment by christophgomez** [comment]
I'm getting this same behavior, Web Player plays for a while, usually around 30 minutes, then get the following errors: 
`GET https://api.spotify.com/v1/melody/v1/check_scope?scope=web-playback 401`

`PUT https://api.spotify.com/v1/track-playback/v1/devices/28d6429210affe550feda5d81061dcc3be5d94e1/state 401`

`POST https://api.spotify.com/v1/melody/v1/logging/jssdk_error 401`

I'm not trying to manually refresh the token as the sdk should do that on it's own. I have almost all scopes too: 
`var scopes = 'playlist-read-private playlist-modify-public playlist-modify-private playlist-read-collaborative user-read-private user-read-birthdate user-read-email user-read-playback-state user-read-currently-playing user-modify-playback-state app-remote-control streaming user-top-read user-read-recently-played user-library-read user-library-modify';`

Can anyone shed some light this?

**Comment by JackRyder** [comment]
@christophgomez see here in where I used the spotify web SDK: https://github.com/JackRyder/SpotiiShuffleWebPlayer/blob/6bcd1c03ea9dc09bb9fed1db169ab13ce568e354/SpotiWebPlayer/Pages/Index.cshtml#L182

You have to set to a function that returns a token, and it will call that function whenever it needs a token.

**Comment by christophgomez** [comment]
@JackRyder Thank you, nice solution. Weird that the the SDK doesn't do this itself.

**Comment by JackRyder** [comment]
The SDK needs to know your refresh token URI, therefore it needs some help which is the callback you assign 👍 It would have been nice if it was just a few parameters and it does the rest, though.
