### ISSUE TITLE
[Feature request] Stream track samples for visualization

### ISSUE THREAD

**Issue by kevbot-git** [spotify/web-playback-sdk#3]
Hi there, thanks for this very cool API, I am looking forward to seeing what people come up with for its use!
I know there must be very careful protection for audio streams to ensure they aren't used in breach of the Terms – though I was wondering if there was a way to access track sample data without needing access to the audio file itself?

**The use case for this is simple**: to add track visualizations.

Is this, at all, a) within the bounds of the Terms, and b) perhaps possible to do in the project's current state or c) in a future release's scope?
Many thanks!

**Comment by arirawr** [comment]
Hi @kevbot-git - 

I'm not a lawyer and can't interpret the Terms for you, but I suggest you take a look at the [Audio Analysis endpoint](https://beta.developer.spotify.com/documentation/web-api/reference/tracks/get-audio-analysis/) offered in the Web API. It provides a *very* detailed representation of the track's audio and may work for your use case. If you need actual audio, you can also access 30 second preview clips for some tracks through the [Get Track endpoint](https://beta.developer.spotify.com/documentation/web-api/reference/tracks/get-track/).

You can use the same access token you use for the Web Playback SDK for both of those endpoints.

Hope that helps! 😄
