### ISSUE TITLE
Can't play track in my test player

### ISSUE THREAD

**Issue by Vietvantue** [spotify/web-playback-sdk#31]
Issue found on May 9th, 2018

Scope(s):
"streaming", "user-read-birthdate", "user-read-email", "user-read-private", "user-modify-playback-state"

Steps to reproduce:
1. Request access_token of premium account
2. Init Spotify.Player
3. Play a track after player is ready with device_id is my player's device_id
4. Observe in Spotify Web Player and my test player

Expected behaviour:
Track must be played in my test player

Actual behaviour:
Track changed state but not play in my test player, but in Spotify Web Player it shows that track is playing in my test player

Code for play track: 
![screen shot 2018-05-10 at 12 26 08](https://user-images.githubusercontent.com/19173549/39853613-6feb2d3c-544d-11e8-9a39-0f7e94ad7a65.png)

I record a video about this case: https://goo.gl/vaQ3nW

**Comment by hughrawlinson** [comment]
Hi @Vietvantue - it looks like you're running into [Chrome's new AutoPlay blocker](https://developers.google.com/web/updates/2017/09/autoplay-policy-changes). It means that you should only start playback once your domain's _Media Engagement Score_ is sufficiently high. We recommend that the first time you do playback, you start it inside the callback to a user interaction event handler. You can read more about the best practices in the link I sent you. I will update our documentation to be more clear on this. Thanks!
