### ISSUE TITLE
Playback SDK bitrate?

### ISSUE THREAD

**Issue by Aweponken** [spotify/web-playback-sdk#32]
Hi! I couldn't get an answer on the forum so I'll try here instead (although this is not a bug). What is the streaming quality for the Playback SDK? I can't seem to find it anywhere. Is it 320kbps MP3?
Thanks in advance!

**Comment by Aweponken** [comment]
Update: I actually got an answer that it's 256kbps. Is that mp3? Or any other compression?

**Comment by bih** [comment]
Hi,

We only offer 256kbps for the Web Playback SDK, and it is using Encrypted Media Extensions (EME) under a different format than MP3. Also to note, this question was already answered under #8.

Let me know (and feel free to re-open) if you have any other questions!
