### ISSUE TITLE
Internet Explorer 11 not working

### ISSUE THREAD

**Issue by MagicMau** [spotify/web-playback-sdk#34]
Issue found on June 1, 2018.

#### Steps to reproduce:
1. recreate quickstart example from https://developer.spotify.com/documentation/web-playback-sdk/quick-start/#
2. try to run it in Internet Explorer 11

#### Actual behaviour:

IE has a couple issues with this. The main issue is that Promise is not defined on IE11. This can be overcome with a polyfill (eg https://github.com/stefanpenner/es6-promise). However, the iframe that's loaded in does not have the polyfill and throws a fatal error on load.

Another minor issue is that the quickstart example is written in ES6 (using lambda functions), but this is easily changed.

It would help for IE to include the following lines in <head> of the embedded iframe's html:

    <script src="https://cdn.jsdelivr.net/npm/es6-promise@4/dist/es6-promise.min.js"></script>
    <script>ES6Promise.polyfill();</script>

or targeting IE11 only:

    <script type="text/javascript"> 
      var ua = window.navigator.userAgent; 
      var msie = ua.indexOf("MSIE "); 
      if (msie > 0 || !!navigator.userAgent.match(/Trident.*rv\:11\./)) 
        document.write('<script src="https://cdn.jsdelivr.net/npm/es6-promise@4/dist/es6-promise.min.js"></scr'+'ipt>'+
        '<script>ES6Promise.polyfill();</scr'+'ipt>'); 
    </script>

**Comment by hughrawlinson** [comment]
Thanks for the feedback! We'll look into it.

**Comment by UlysseM** [comment]
Maybe related, the latest version (v1.6.0-83173f1) is not working on chrome (67.0.3396.62) for me, but it is working on firefox.
The "getOAuthToken" function is not being called back.
I've made a small video to show it up: https://www.useloom.com/share/49081dcd477941e9b1688e1ef0321aae

**Comment by MagicMau** [comment]
I've noticed this has been fixed. Thanks for that!

If it helps, this is the Javascript that I use to run the web player in IE11 instead of the example code provided (which uses Ecmascript 6 specific features):

    <!DOCTYPE html>
    <html>
    <head>
      <title>Spotify Web Player</title>
      <script src='https://cdn.jsdelivr.net/npm/es6-promise@4/dist/es6-promise.min.js'></script>
      <script>ES6Promise.polyfill();</script>
    </head>
    <body>
      <h1>Spotify Web Player</h1>
      
      <div id='log'>

      </div>
      <script src='https://sdk.scdn.co/spotify-player.js'></script>
      <script>
        window.onSpotifyWebPlaybackSDKReady = function() {

          function log(message) {
            document.getElementById('log').innerHTML  += '<pre>' + message + '</pre>';
          }

          var token = '{accessToken}';
          var player = new Spotify.Player({
            name: 'Spotify Web Player',
            getOAuthToken: function(cb) { cb(token); }
          });

          // Error handling
          player.addListener('initialization_error', function(error) { log('initialization_error: ' + JSON.stringify(error)); });
          player.addListener('authentication_error', function(error) { log('authentication_error: ' + JSON.stringify(error)); });
          player.addListener('account_error', function(error) { log('account_error: ' + JSON.stringify(error)); });
          player.addListener('playback_error', function(error) { log('playback_error: ' + JSON.stringify(error)); });

          // Playback status updates
          player.addListener('player_state_changed', function(state) { log('player_state_changed: ' + JSON.stringify(state)); });

          // Ready
          player.addListener('ready', function(result) {
            log('player ready: ' + JSON.stringify(result));
          });

          // Not Ready
          player.addListener('not_ready', function(result) {
            log('player not ready: ' + JSON.stringify(result));
          });

          // Connect to the player!
          player.connect();
        };
      </script>
    </body>
    </html>
