### ISSUE TITLE
Player does not initialize when embedded in another site

### ISSUE THREAD

**Issue by sajsanghvi** [spotify/web-playback-sdk#36]
I have the Spotify Web Playback SDK working great on my own website. 

When I try to embed my site into another site, the player doesn't initialize. 

Seeing an error like "EME_API_NOT_SUPPORTED". Any ideas?

**Comment by sajsanghvi** [comment]
easy solution: add this to the iframe
allow="geolocation *; microphone *; camera *; midi *; encrypted-media *"

**Comment by arirawr** [comment]
As you mentioned in your comment, yes, you need to add `allow="encrypted-media"`. The others you mentioned are not required.

**Comment by MarkPieszak** [comment]
Make sure you have `autoplay` there as well in *allow=*.

Might be related to #67
