### ISSUE TITLE
Init Spotify.Player from existing Device

### ISSUE THREAD

**Issue by sajsanghvi** [spotify/web-playback-sdk#37]
Instead of creating a new player like this: 
```
const spotifyPlayer = new Spotify.Player({
            name: 'xxx',
            getOAuthToken: cb => { cb(access_token); }
          });
```
is there a way to connect that Spotify.Player to an existing device instance? for example my iPhone or my Desktop Client?

**Comment by arirawr** [comment]
Hi @sajsanghvi -

This SDK is made for creating a new Spotify Player in the user's browser. If you want to control other devices, you should instead use the [Spotify Connect Web API](https://developer.spotify.com/documentation/web-api/reference/player/), which allows you to get and control a user's devices.

Hope that helps! If you have any issues using the Connect API, you can file an issue at https://github.com/spotify/web-api

**Comment by gian-luca1416** [comment]
Hi @arirawr 

Is it possible with the Connect Web API to get events like 'next song'?
