### ISSUE TITLE
ready event is not fired when using SDK on http site

### ISSUE THREAD

**Issue by JanneHarju** [spotify/web-playback-sdk#38]
Issue found on 6.7.2018

#### Scope(s):
            'user-read-private',
            'user-modify-playback-state',
            'user-read-playback-state',
            "streaming",
            "user-read-birthdate",
            "user-read-email"

#### Steps to reproduce:
1. Provide your web site with http protocol
2. login in to spotify
3. add https://sdk.scdn.co/spotify-player.js dynamically to your site after logged in successfully
4. this will fire onSpotifyWebPlaybackSDKReady
5. after that event is fired I create new player
6. call player.connect(), it returns true.
7. add ready event listener, this is never fired and I will not get deviceId and other stuff with data.
8. when I try call api(not player) to set volume I get 404 and message said that No active device found what make sense because ready never fired.

#### Expected behaviour:
Everything is working when my site is on https but when I switch to http this got broken. Should SDK work with http also? I expect that ready event occure also with http sites.

#### Actual behaviour:
Player ready event is not fired when site is provided with http protocol.

#### Additional Info
All works when I debug my Angular application with http://localhost:4200 but when I have published my frontend to cloud and use http instead of https this problem occures.
Here is my related code https://github.com/JanneHarju/MultiSourcePlayList/blob/master/src/app/services/spotify-playback-sdk.service.ts#L30

**Comment by arirawr** [comment]
Hi @JanneHarju - 
You will need to use HTTPS instead of HTTP. In Chrome, [EME will not work in non-secure contexts](https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/tXmKPlXsnCQ/discussion) (ie. over HTTP). [Localhost is considered a secure context](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts), so it will work there.

**Comment by JanneHarju** [comment]
@arirawr thank you. I did know that but I did also forgot it already. Sorry for unnecessary ticket.
