### ISSUE TITLE
Error when calling seek(): no list was loaded

### ISSUE THREAD

**Issue by logason** [spotify/web-playback-sdk#39]
Hi! 👋

I stumbled upon a error when hacking with the new web sdk:

Issue found on 07/10/18.

#### Scope(s):
```
  'streaming',
  'user-read-birthdate',
  'user-read-private',
  'user-modify-playback-state'
```

#### Steps to reproduce:
1. Start a song with the web API by posting to `/v1/me/player/play` with three song uris (current and two next up)
2. Call `player.seek(positionInMs)` with the position I want to go to in the current song. The promise is resolved with the value `3` but then immediately the following error is thrown and the position stays unchanged.

```
playback_error Cannot perform operation; no list was loaded.
```

#### Expected behaviour:
Current position in song should be updated.

#### Actual behaviour:
Current position in song is not updated and an error is thrown.

Love this API btw! keep up the good work 👏

**Comment by arirawr** [comment]
I've been able to reproduce this and we're looking into it. Thanks for the report!

**Comment by arirawr** [comment]
Hi @logason - looks like that error occurs when you have no song currently playing locally. This can occur if you call `seek()` too quickly after starting a song with the Web API (you can verify this behaviour by setting a 3000ms timeout before your call to seek).

You can try calling seek in a callback from your Web API call or in the `player_state_changed` of the Web Playback SDK.

Hope that helps!

**Comment by logason** [comment]
Thanks @arirawr! Moving seek to the next `player_state_changed` event after I hit play solves it 🙏
