### ISSUE TITLE
TypeScript Types

### ISSUE THREAD

**Issue by NeoLegends** [spotify/web-playback-sdk#4]
Hey!

First of all, thank you SO much for the new web playback SDK. We've been waiting for something like it for a really long time now.

We wrote some TypeScript typings for the new Web playback SDK. If this aligns with your current goals, we would be very pleased if they became "official" in the sense that you would either notify us if you change the web playback SDK (so that we can update the typings) or if you would take over their maintenance.

Would love to hear your feedback!

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/22559

**Comment by hughrawlinson** [comment]
Awesome work @NeoLegends! Would you mind writing up a tutorial/demo on how to use them, or point me to some resources/an example app that shows them in action? Once we've had a chance to play around with them, I'm sure we'd be happy to link to them from our website. We're not typescript experts, so it'd be great if you continue to maintain them.

**Comment by NeoLegends** [comment]
Sure! We're currently using them for our social jukebox app Festify over at https://github.com/Festify/app/tree/fit-rewrite. Relevant file is https://github.com/Festify/app/blob/fit-rewrite/src/actions/playback-spotify.ts (early WIP).

Instructions:
1. Install the types as dependency:
    ```bash
    yarn add -D @types/spotify-web-playback-api
    # alternatively with npm
    npm install -D @types/spotify-web-playback-api
    ```

1. Somewhere in the project before using the SDK:
    ```ts
    import '@types/spotify-web-playback-sdk';
    ```

That's it. :) TypeScript will then understand the new globals and lets you use them in a typed fashion.

**Comment by bih** [comment]
@NeoLegends We don't currently have anything in place to notify maintainers about updates to the library, but all changes are posted to the [News](https://beta.developer.spotify.com/community/news/) section of the Spotify for Developers website.

**Comment by NeoLegends** [comment]
Actually why don‘t you just post here? :D should work just as well.

**Comment by bih** [comment]
@NeoLegends We can definitely do that for now 👍  Ideally we'd like to have something in place to notify all of our community contributors about changes in a timely manner, similarly to how other great developer platforms do, stay tuned for that!

**Comment by bih** [comment]
@NeoLegends Just to keep our GitHub issue tracker as up-to-date and consistent as possible, I'm going to close this issue. I have noted your details and we'll let you know about changes as and when we make them to the Web Playback SDK.

Finally, thanks for all of your work on this, we're big fans! We'd also love to send you some cool Spotify swag - drop us an email and we'll sort something out 🎁  😉

**Comment by NeoLegends** [comment]
Awesome!

**Comment by Gabsch** [comment]
The "playback-spotify.ts" link seems to have been changed to this link:

https://github.com/Festify/app/blob/beta/src/actions/playback-spotify.ts

**Comment by NeoLegends** [comment]
Exactly, thanks for pointing that out. I updated the links in my original comment.

**Comment by NeoLegends** [comment]
Added definitions for `not_ready` event. https://github.com/DefinitelyTyped/DefinitelyTyped/pull/27566
