### ISSUE TITLE
How do I indicate that a device is connected?

### ISSUE THREAD

**Issue by stefanprobst** [spotify/web-playback-sdk#40]
Currently, it is not possible to determine through the Web Playback SDK if the device is connected.

`connect()`ing the first time will result in a `ready` event with a device ID, and I can also check the resolved Promise from `connect()` if the connection has been successfully established.
But upon `disconnect()`ing, the device ID is preserved, and `disconnect` always returns void.

EDIT: Maybe I am reading the docs wrong and the `ready`/`not_ready` events are supposed to signal if the device is connected? Then the problem seems to be that `not_ready` does not fire when `disconnect()`ing.

**Comment by bih** [comment]
Hello @stefanprobst,

Thanks for reaching out. It is actually possible to do this by running the following code (as per our [API Reference Documentation](https://developer.spotify.com/documentation/web-playback-sdk/reference/#)):

```js
player.getCurrentState().then(state => {
  let isDeviceConnected = state !== null;

  if (isDeviceConnected) {
    console.log("Device is connected!");
  } else {
    console.log("Device is not connected");
  }
})
```

I'll go ahead and close this as this is resolved. Feel free to open a new issue if you have any other problems! 👍

**Comment by stefanprobst** [comment]
Could you please clarify what the SDK means by the "ready", "connected" and "selected" states? AFAICT `getCurrentState` does *not* signify if the player is connected, but if it is selected, i.e. the active player. When I call player.connect(), getCurrentState will still return null.

**Comment by tobika** [comment]
Hi, I have exactly the same problem. After long absent of activity sometimes the Player deletes the deviceId. As @stefanprobst said `getCurrentState` is not helpful because even if the Player is well connected but not playing the return is `null`.

Is there another way to make a check if Player is operational? Otherwise I check for 404 or 401 upon action and reload everything. @bih
