### ISSUE TITLE
Issues integrating Spotify's Web Playback SDK on VueJS

### ISSUE THREAD

**Issue by rahch1982** [spotify/web-playback-sdk#43]
Greetings,

I'm working on a new project using VueJS through Vuetify's Cordova template. I've been trying to integrate Spotify's Web Playback SDK on my project, but I haven't been able to achieve it. 

The SDK is loaded correctly on browser and I'm able to instantiate a Player object inside an async method, but it fails to create a local connect device in order to play an Spotify URI (device_id is undefined). 

When I log the Player object on the browser as a string (JSON.stringify), I get the following:

```
{
    "_options": {
        "name": "Test Web Playback SDK",
        "id": "17203cc66af7fdc5a69dfcbbea3e9d69565428c1",
        "volume":1
    },
    "_messageHandlers":{},
    "_eventListeners":{},
    "_connectionRequests":{},
    "_getCurrentStateRequests":{},
    "_getVolumeRequests":{},
    "isLoaded":{"_c":[],"_s":0,"_d":false,"_h":0,"_n":false}
}
```

Notice the value for "isLoaded".

If I create an static page (not on VueJS), import the spotify-player.js script, and I create a Player object using a valid token, when I log the Player object on the browser as a string (JSON.stringify), I get the following:

```
{
    "_options": {
        "name": "Test Web Playback SDK",
        "id": "17203cc66af7fdc5a69dfcbbea3e9d69565428c1",
        "volume":1
    },
    "_messageHandlers":{},
    "_eventListeners":{},
    "_connectionRequests":{},
    "_getCurrentStateRequests":{},
    "_getVolumeRequests":{},
    "isLoaded":{}
}
```

It creates a local connect device as expected. Notice the value for "isLoaded".

#### Steps to reproduce:
1. Initiate a new VueJS project using a pre-made Vue CLI template
2. On "index.html", include Web Playback SDK
3. On App.vue, create mounted hook with the following:

```
mounted () {
    window.onSpotifyWebPlaybackSDKReady = () => {}
}
```

4. On Home component, or any other,  create the following methods:

```
methods: {
    waitForSpotifyWebPlaybackSDKToLoad: async function () {
        return new Promise(resolve => {
            if (window.Spotify) {
                resolve(window.Spotify)
            } else {
                window.onSpotifyWebPlaybackSDKReady = () => {
                    resolve(window.Spotify)
                }
            }
        })
    },
    initiatePlayer: async function () {
        const { Player } = await this.waitForSpotifyWebPlaybackSDKToLoad()
        const sdk = new Player({
            name: 'Test Web Playback SDK',
            volume: 1.0,
            getOAuthToken: callback => { callback(token) }
        })
        console.log(JSON.stringify(sdk))
        // Error handling
        sdk.addListener('initialization_error', ({ message }) => { console.log('Initialization_error: ' + message) })
        sdk.addListener('authentication_error', ({ message }) => { console.log('Authentication_error: ' + message) })
        sdk.addListener('account_error', ({ message }) => { console.log('Account_error: ' + message) })
        sdk.addListener('playback_error', ({ message }) => { console.log('Playback_error: ' + message) })
        // Playback status updates
        sdk.addListener('player_state_changed', state => {
            // Update UI information on player state changed
        })
        // Ready
        sdk.addListener('ready', ({ deviceId }) => {
            console.log('Ready with Device Id: ', deviceId)
        })
        // Not Ready
        sdk.addListener('not_ready', ({ deviceId }) => {
            console.log('Not ready with device Id: ', deviceId)
        })
        sdk.connect()
    }
}
```

5. On same component, create a hook in which Player object will be instantiated

```
mounted () {
    this.initiatePlayer()
}
```

#### Expected behaviour:

Local Connect device on browser created successfully.

#### Actual behaviour:

Local Connect device on browser is undefined.

**Comment by fafcrumb** [comment]
You are trying to make a Cordova application here correct?
If so I don't believe that would be a supported environment for this SDK

**Comment by mathewdgardner** [comment]
For those from Google, like me, `deviceId` should be `device_id`. `deviceId` is undefined because it is not the first arg in the callback function. Instead, it's being destructured from the first arg that is an object.

**Comment by tobika** [comment]
@rahch1982 have you resolved your issue with the last comment?

I am doing a cordova ionic app and the sdk works pretty well, even maybe if not supported.
The only trouble that stays is that after around 5min the stream goes in pause mode, probably because the system forces the app into sleep mode.
Using the background-mode plugin helps but it can't keep the http requests going. Only local js execution in background works all the time.

**Comment by rahch1982** [comment]
Hi @tobika , I'm sorry for the late response. Yes, actually we've resolved the issue by following the instructions on last comment . Everything is working just fine.

By the way, thanks for the advice @mathewdgardner 

Our testing team hasn't experienced any issues related to background tasks. Let me draw their attention on this so I can confirm.

**Comment by tobika** [comment]
@rahch1982 thanks for your reply, I got the background problem fixed somehow with the cordova background-mode plugin.

**Comment by rahch1982** [comment]
Good to know you have solved the issue @tobika  . I'm going to proceed to close this thread then.
