### ISSUE TITLE
Spotify Web Playback API throwing script error on edge browser

### ISSUE THREAD

**Issue by desantir** [spotify/web-playback-sdk#44]
Issue found on 8/31/2018.

#### Scope(s):

Error in edge browser, works in Chrome

#### Steps to reproduce:
1. Run your sample player connect function
2. Console error

#### Expected behaviour:

Works on Edge

#### Actual behaviour:

SCRIPT16389: SCRIPT16389: Unspecified error.
spotify-player.js (2,10594)

**Comment by desantir** [comment]
The API uses localStorage - not allowed in edge when the HTML source file is local (i.e. file://).  Great for running the example.

**Comment by arirawr** [comment]
Hey @desantir, sounds like you've found the solution here. You should also be able to run it locally by making a small local server, ie. `python -m SimpleHTTPServer 8000`
