### ISSUE TITLE
Disable web SDK Autoplay

### ISSUE THREAD

**Issue by novostack** [spotify/web-playback-sdk#51]
Issue found on 15 November 2018.

#### Scope(s):

I've integrated spotify web playback SDK on my website which lets users play songs from their library upon getting authorisation from Spotify.

#### Steps to reproduce:
1. Integrate spotify SDK and a player

#### Expected behaviour:

Should actually play songs when play button is hit.

#### Actual behaviour:
Plays song on page load

**Comment by arirawr** [comment]
Hi @novostack - the Web Playback SDK does not autoplay. Could you post the code you're using?

**Comment by novostack** [comment]
Hi @arirawr 

Here's the code - https://stackoverflow.com/questions/53388190/disable-autoplay-on-spotify-sdk?noredirect=1#comment93652637_53388190

**Comment by arirawr** [comment]
@novostack thanks for the link.

I answered you over there, but this seems to be a problem with your code, as you're making a call to the Web API `/player/play` in the Web SDK's `ready` callback, which is called automatically and will result in autoplay-like behaviour. If you remove the calls to that API from the callback you won't get automatic playback anymore.
