### ISSUE TITLE
Get existing player and events

### ISSUE THREAD

**Issue by gian-luca1416** [spotify/web-playback-sdk#62]
Hello

(Question)

I was working with the Web API when I realized that I need to know when, for example, a song ends. I ended up on the Web Playback SDK. So I get how that works, with the new player and that stuff. But how is it possible (and with what API), to get events for an existing player? Or to create an object in form of a player and get events?

It has to be possible somehow, the spotify web app can do it. I mean you can listen without creating a new player.

And I am aware of the possible dublicate of some questions here but there are no answers. Just wondering if something has changed since then.

Thanks for your help.
Gian-Luca

**Comment by fafcrumb** [comment]
Short answer, it's not possible.
From what I've seen, Spotify seems determined to keep that functionality limited to themselves and their partners.
You can poll the API endpoint to get the current player state, as your app gains more users you'll start running into the rate limit pretty quickly.
Hope that helps!

**Comment by arirawr** [comment]
Hey @gian-luca1416 - this isn't supported yet, but you can follow this issue for updates: https://github.com/spotify/web-api/issues/492

You can also poll as @fafcrumb mentioned.

**Comment by gian-luca1416** [comment]
Alright thanks for your answers!
