### ISSUE TITLE
Web Playback SDK support with Electron

### ISSUE THREAD

**Issue by jsrbn** [spotify/web-playback-sdk#7]
Issue found on *January 4th 2018*.

#### Steps to reproduce:
1. Use Github's [Electron](https://electronjs.org/) and create an Electron application
2. Use the Spotify Web Playback SDK as described in the docs
3. Connect the player with a valid access token

#### Expected behaviour:
1. The player connects and gets a device id
2. If the player is selected as active device, it should work and play the current track

#### Actual behaviour:
1. The player connects and gets a device id
2. The following error appears:  `Uncaught (in promise) {code: "LIST_PLAYER_NO_TRACK_PLAYER", message: "No supported keysystem was found.", unrecoverable: false, listPlayerIgnore: false, debug: Object}`

**Comment by hughrawlinson** [comment]
Hi @jsrbn - it looks like Electron doesn't support Widevine CDM that's required by the Web Playback SDK. You should try [this guide to enable Widevine in Electron](https://github.com/electron/electron/blob/master/docs/tutorial/using-widevine-cdm-plugin.md) and report back whether or not you got it working 😄

**Comment by jsrbn** [comment]
Hi! I followed the instructions given in the guide and the error disappeared. But now I get a new one and found no way to fix it. The error object is: `{code: "LIST_PLAYER_NO_TRACK_PLAYER", message: "Unable to create the CDM for the key system com.widevine.alpha.", unrecoverable: false, listPlayerIgnore: false, debug: Object}`

**Comment by Rudloff** [comment]
You can also try [this package](https://github.com/quanglam2807/electron-widevinecdm) that makes it easy to include Widevine into Electron.

**Comment by bih** [comment]
Any luck with this @jsrbn?

**Comment by jsrbn** [comment]
Unfortunately not - getting still an error 😕 @bih

**Comment by Rudloff** [comment]
I tried using the SDK in an Electron app with Widevine and I get the same error:
```
index.html:1 Uncaught (in promise) r {code: "LIST_PLAYER_NO_TRACK_PLAYER", message: "No supported keysystem was found.", unrecoverable: false, listPlayerIgnore: false, debug: Object}code: "LIST_PLAYER_NO_TRACK_PLAYER"debug: ObjectlistPlayerIgnore: falsemessage: "No supported keysystem was found."unrecoverable: false__proto__: Error
    at Object.<anonymous> (https://sdk.scdn.co/embedded/index.js:2:36667)
    at e (https://sdk.scdn.co/embedded/index.js:2:101)
    at Object.<anonymous> (https://sdk.scdn.co/embedded/index.js:2:97435)
    at Object.<anonymous> (https://sdk.scdn.co/embedded/index.js:2:116964)
    at e (https://sdk.scdn.co/embedded/index.js:2:101)
    at Object.<anonymous> (https://sdk.scdn.co/embedded/index.js:2:93929)
    at e (https://sdk.scdn.co/embedded/index.js:2:101)
    at Object.<anonymous> (https://sdk.scdn.co/embedded/index.js:2:93794)
    at e (https://sdk.scdn.co/embedded/index.js:2:101)
    at Object.<anonymous> (https://sdk.scdn.co/embedded/index.js:2:38344)
```

The same code works in a regular browser and the same Electron app can correctly play DRM media on other webpages.

**Comment by alminde** [comment]
It works for me with `electron-widevinecdm` and Electron 1.7.11 on macOS.

At first I couldn’t understand what I was doing wrong, but it turned out that I had forgotten to add `webPreferences: { plugins: true }`. 😁

**Comment by Rudloff** [comment]
I tested again and now it works! I'm not sure if something changed with my setup or if you updated the SDK.

**Comment by bih** [comment]
Glad to hear that you got it working! 🎉 

Just to be clear to everyone, if you plan on building an application for distribution with Electron, you are responsible for making sure you have the correct licenses with Widevine to do so. As [Electron's article on Widevine](https://github.com/electron/electron/blob/master/docs/tutorial/using-widevine-cdm-plugin.md) clearly states, 

 There's a reason from Electron's part as to why Widevine isn't bundled by default.

Other than that, it seems like good news, so I'll go ahead and close this issue. Feel free as always to re-open the issue if there are problems 👍
