### ISSUE TITLE
What is the audio quality in the Web Playback SDK?

### ISSUE THREAD

**Issue by cesutherland** [spotify/web-playback-sdk#8]
From using the various Spotify apps, it seems that audio quality is set up per-device.  Looking over the docs for the new web playback SDK I don't see any references to audio quality.

What is the audio default audio quality here?

Are there plans to allow changing it?

Just curious!

**Comment by bih** [comment]
Hey @cesutherland, thanks for reaching out!

The Web Playback SDK's standard quality is the [same as the Web Player](https://support.spotify.com/us/article/high-quality-streaming/), which is AAC 256kbit/s. We don't have any plans in the near future to allow changing the audio quality in the SDK.

Hope that helps. Is there a particular use case you have that I can help with? 🙂

**Comment by cesutherland** [comment]
All clear!  The only case I have is giving users a preference :-)

Thanks!
