### ISSUE TITLE
Safari 12.1 MacOS Mojave v10.14.4 - the player crashes on initialization

### ISSUE THREAD

**Issue by useless-stuff** [spotify/web-playback-sdk#89]
Issue found on *2019-10-07*.

#### Scope:
Browser Safari 12.1 

#### Steps to reproduce:
Init the player ( code snippet from the Spotify SDK doc ) in Safari 12.1 will produce the error "Failed to initialize player".
Tested through both HTTPS and HTTP.

#### Expected behavior:
It works well in Chrome and Firefox, I suppose should work also in Safari ( or not? :) ) 

#### Actual behaviour:
Client crashes and triggers event "initialization_error"

Request:
Is it possible to add more details to the error?

**Comment by tomjaimz** [comment]
Hi @useless-stuff.

Safari is not currently supported.  You can check the supported browsers at https://developer.spotify.com/documentation/web-playback-sdk/#supported-browsers

Thanks,
Tom.

**Comment by useless-stuff** [comment]
👏👏 for me! 
So sorry 😓
