### ISSUE TITLE
Quick-start tutorial does not produce working playet

### ISSUE THREAD

**Issue by RyanMKrol** [spotify/web-playback-sdk#9]
Issue found on 14/1/18.

#### Steps to reproduce:
1. Go to https://beta.developer.spotify.com/documentation/web-playback-sdk/quick-start/, and copy source code into an html file.
2. Host this file on a server somewhere.
3. Load the page, and see an error in the log: "Failed to initialize player".

#### Expected behaviour:
A default player that should show up as a result of the quick start.

#### Actual behaviour:
No player, and an error in the log.

**Comment by bih** [comment]
Hi @RyanMKrol,

Thanks for reaching out. I can't seem to replicate the error. Do you have Spotify Premium/Family? The Web Playback SDK is currently not supported on Spotify Free

**Comment by RyanMKrol** [comment]
Sure thing:

- I have a Premium Account
- MacOS, latest version of chrome

I'll try and reproduce a bit later, just heading off to work.

**Comment by bih** [comment]
Just checking up - are you still having issues with this, Ryan?

**Comment by RyanMKrol** [comment]
Hey, sorry I keep forgetting to come back to this.

So if I host the file locally, the API seems to work just fine, but when I host it on a server somewhere, I get nothing but errors.

**Comment by arirawr** [comment]
Hi @RyanMKrol - are you using HTTPS on your server? In Chrome, [EME will not work in non-secure contexts](https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/tXmKPlXsnCQ/discussion) (ie. over HTTP). [Localhost is considered a secure context](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts), so it will work there.

**Comment by RyanMKrol** [comment]
Hey, thanks! That will almost certainly be the issue, I should have read a bit more into EME before posting.
