### ISSUE TITLE
Trouble transfering a queue and selecting the Spotify SDK player as device.

### ISSUE THREAD

**Issue by Ferrax** [spotify/web-playback-sdk#99]
Dear all, 

1. Since yesterday I am encountering problems with the Spotify Connect player in two different ways. The first being selecting and connecting the Spotify Connect player. This used to work fine, however, now I often get a 403 (forbidden) when I try to switch to the SDK player, and it barely works. I thought it was my code, however, this also seems to happen (as often times the player does not switch to the SDK player) when I have the Spotify application open on my MacBook or PC and try to connect to the Web SDK Player from there. Before yesterday this was not the case.

2. The second problem is that IF the player from the Web Playback SDK is active, that I cannot change the queue it is currently playing. It starts playing music, other than the ``context_uris`` and ``offset`` I provide to the Spotify API. Again, this does not happen if my MacBook, PC, phone or any other device is selected. If I select such a device, perform a request to the API, the queue gets changed properly. However, if I have a particular queue, switch to the Player provided by the web-playback-sdk this queue gets deleted and it starts playing random songs. In some cases, only the first track I provide starts playing, but as I press next, it starts playing random songs.

Issue found on 16th of January, 2020. 

#### Scope(s):
streaming, user-modify-playback-state

##### Problem one 
1.1. Create a device through the web-playback-sdk, try switching playback to that device using code and the Spotify [transfer playback endpoint](https://developer.spotify.com/console/put-user-player/) or one of the apps on one of your Spotify devices.
##### Problem two
2.1. Select the Spotify player created by the SDK. Use the Spotify API and the [play / resume](https://developer.spotify.com/console/put-play/) endpoint to provide a list with ``context_uris`` and ``offset``. If the song that you passed to the API starts playing, skip to the next. 

#### Expected behaviour:
1. Upon selecting the SDK player from either the official Spotify applications or by PUTting the ``device_id`` using the API, the playback should be transferred to that player.
2. If I pass ``context_uris`` with an offset to the Spotify API, the player created by the web-playback-sdk should play those songs.

#### Actual behaviour:
1. Playback does not get transferred. I often get a 403 error, making me think that it's my code. However, switching to OTHER devices using my code is no problem. Also, using official Spotify applications, the playback often does not get transferred when the SDK-player is selected.
2. IF the Spotify SDK player is active, and I change the queue by PUTting the start / resume playback endpoint, more often than not the queue is not transferred. It will play one song at most, and then start playing (random) songs. However, when the Spotify application on my MacBook is the main device, this problem does not occur and the queue / offset works properly.

Edit: 18th of January - made post a little more coherent.

**Comment by thomasboyt** [comment]
Oh wow, I came here to make this exact bug report, glad it's not just an issue on my end.

I have not encountered the 403 issue mentioned yet. However, I have consistently encountered the same problem with the queue not being transferred. I've found that it's been playing from _my play queue on my most recently used device_, which is fascinating, since I thought play queues were supposed to be per-device. I also only started seeing this issue today.

**Comment by anker2000** [comment]
I'm not sure this is at all related, but since Thursday, I've been having issues with just getting the SDK to play the right song. Intermittently one specific song will start playing, even if I've fed the SDK a different URI. It will then sometimes play a couple of songs like it should, and then all of a sudden that same specific song will start playing again. I don't believe that specific song is queued up anywhere, it just keeps returning still though.

**Comment by Ferrax** [comment]
These issues seem very much like the ones I have encountered! What I also found that they are rather inconsistent. For example, I transfer a queue, sometimes it plays one song, but starts playing unrelated songs when I press next. Sometimes it doesn't do anything and deletes my queue. And there are other times where it starts playing random songs from a playlist.

I hope we can get a response to this if need be.

**Comment by adrianosbr** [comment]
Having the same issue here.

**Comment by UlysseM** [comment]
I have also been getting weird issue recently:
- The "me/player/play" action of a track plays a completely unrelated track
- The "me/player/pause" action sometimes works, but music comes back shortly after.
- I asked for a single track to be played, and similar tracks keeps playing at the end of it.

In my case, I don't personally "swap" playback endpoint, (I often have only one), but I always specify the player ID when sending "play" requests.

It makes my app feel very sloppy although it has been working fine for over a year...

**Comment by humusdigital** [comment]
I have the same issue. Spotify is prioritizing the play queue tracks over custom devise that is trying to play a track load with js me/player/play.

**Comment by joshubrown** [comment]
Thank you for opening an issue, @Ferrax!  I am looking into this here at Spotify. I'll post in this thread as soon as we have an update to share.

**Comment by vjhameed** [comment]
I am experiencing the same issue. Spotify dosent play the track that i pass in rather it plays the tracks that are in thext next_tracks array in state object. I have fixed it temporarily by creating a custom duration slider for spotify. But we really need a fix for this.

Thanks

**Comment by joshubrown** [comment]
Thanks again for the feedback, everyone. We made some updates today that should resolve the problem with API-initiated playback. If you are still experiencing an issue with the player APIs then please share details with us [over in the Web API repo.](https://github.com/spotify/web-api/issues/new) 🙂

**Comment by adrianosbr** [comment]
Thank you so much! I just tried my app and it seems to be working flawlessly now!
